---
collections:
  - name: homelab.common_roles
    source: https://github.com/Knighten-Homelab/ansible-common-roles.git
    type: git
    version: 1.3.0
  - name: community.docker
  - name: freeipa.ansible_freeipa
  - name: awx.awx
