---
collections:
  - name: homelab.common_roles
    source: git@github.com:Johnny-Knighten/ansible-homelab-common-roles.git
    type: git
    version: 1.3.0
  - name: community.docker
  - name: freeipa.ansible_freeipa