galaxy_info:
  author: Johnny Knighten
  description: Cloudflare DDNS Deployed Via Docker Compose
  company: Knighten Uniforms
  license: Apache-2.0
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
    - name: Debian
      versions:
        - bookworm
