---
- name: Create AWX Resources For Cloudflare DDNS Deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure required vars are present
      ansible.builtin.assert:
        that:
          - awx_target_org is defined
          - awx_target_inv is defined
          - awx_git_credential is defined
          - awx_project_branch is defined
          - host is defined
          - hostname is defined
          - host_groups is defined
          - ipaclient_domain is defined
          - ipaclient_realm is defined
          - ipaclient_servers is defined
          - cloudflare_ddns_records is defined
        fail_msg: "Required variables are missing. Please provide them using --extra-vars."

    - name: Verify that the AWX credentials are provided as environment variables
      ansible.builtin.fail:
        msg: AWX credentials are missing. Ensure CONTROLLER_HOST, CONTROLLER_USERNAME, and CONTROLLER_PASSWORD are set as environment variables.
      when: not (lookup('env', 'CONTROLLER_HOST') and lookup('env', 'CONTROLLER_USERNAME') and lookup('env', 'CONTROLLER_PASSWORD'))

    - name: Check if the organization exists
      ansible.builtin.set_fact:
        org_exists: >-
          {{
            lookup(
              'awx.awx.controller_api',
              'organizations',
              query_params={'name': awx_target_org}
            )
          }}

    - name: Fail if the organization does not exist
      ansible.builtin.fail:
        msg: AWX Organization '{{ awx_target_org }}' does not exist.
      when: org_exists | length == 0

    - name: Check if the inventory exists
      ansible.builtin.set_fact:
        inv_exists: >-
          {{
            lookup(
              'awx.awx.controller_api',
              'inventories',
              query_params={'name': awx_target_org}
            )
          }}

    - name: Fail if the inventory does not exist
      ansible.builtin.fail:
        msg: AWX Inventory '{{ awx_target_inv }}' does not exist.
      when: inv_exists | length == 0

    - name: Create host resource
      awx.awx.host:
        name: "{{ host }}"
        description: Cloudflare DDNS VM
        inventory: "{{ awx_target_inv }}"
        state: present
        variables:
          hostname: "{{ hostname }}"

    - name: Added host to groups
      awx.awx.group:
        inventory: "{{ awx_target_inv }}"
        preserve_existing_hosts: true
        preserve_existing_children: true
        hosts:
          - "{{ host }}"
        name: "{{ item }}"
      loop: "{{ host_groups }}"

    - name: Create project
      awx.awx.project:
        name: Homelab - Cloudflare DDNS
        state: present
        organization: "{{ awx_target_org }}"
        scm_type: git
        scm_url: git@github.com:Johnny-Knighten/homelab-cloudflare-ddns.git
        scm_branch: "{{ awx_project_branch }}"
        scm_update_on_launch: false
        scm_credential: "{{ awx_git_credential }}"

    - name: Create job template
      awx.awx.job_template:
        name: Deploy - Cloudflare DDNS (Containerized)
        job_type: run
        inventory: "{{ awx_target_inv }}"
        project: Homelab - Cloudflare DDNS
        playbook: ansible/deploy-docker-compose-cloudflare-ddns.yml
        become_enabled: true
        credentials:
          - Ansible Service Account - Homelab
          - Cloudflare - knighten.io Zone Edit API Key
          - FreeIPA - Homelab Join Secrets
        extra_vars:
          host: "{{ host }}"
          cloudflare_ddns_records: "{{ cloudflare_ddns_records }}"
          ipaclient_domain: "{{ ipaclient_domain }}"
          ipaclient_realm: "{{ ipaclient_realm }}"
          ipaclient_servers: "{{ ipaclient_servers }}"
