---
- name: Setup Cloudflare DDNS Deployed Via Docker Compose
  hosts: "{{ host }}"
  become: true
  vars:
    host: localhost
  roles:
    - role: homelab.common_roles.set_hostname
      vars:
        set_hostname_hostname: "{{ hostname }}"
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        ipaclient_domain: homelab.lan
        ipaclient_realm: HOMELAB.LAN
        ipaclient_servers: ipa.homelab.lan
        ipaclient_mkhomedir: yes
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
    - role: cloudflare-ddns
