---
name: Manual - Deploy/Destroy Environment
run-name: Manual ${{ github.event.inputs.actionSelection }} On ${{ github.event.inputs.environment }} Using ${{ github.event.inputs.releaseRef }}

on:
  workflow_dispatch:
    inputs:
      actionSelection:
        type: choice
        required: true
        description: "Action to Perform"
        options:
          - Deploy
          - Destroy
      environment:
        type: choice
        required: true
        description: "Deployment Environment"
        options:
          - prod
          - test
      releaseRef:
        type: string
        default: main
        description: "Git Ref (Branch/Tag) Checked Out During Execution"

jobs:
  deploy:
    name: Manual Deploy
    if: ${{ github.event.inputs.actionSelection == 'Deploy'}}
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-apply-and-deploy-app-via-awx.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      awx-resource-creation-playbook: create-awx-cloudflare-ddns-deployment-resources.yaml
      awx-deploy-template-name: Cloudflare%20DDNS%20%28Containerized%29%20-%20Deploy
      ref: ${{ github.event.inputs.releaseRef }}
    secrets:
      VAULT_URL: ${{ github.event.inputs.environment == 'test' && secrets.VAULT_URL_TEST || secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ github.event.inputs.environment == 'test' && secrets.VAULT_TOKEN_TEST || secrets.VAULT_TOKEN }}

  destroy:
    name: Manual Destroy
    if: ${{ github.event.inputs.actionSelection == 'Destroy'}}
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-destroy-and-app-cleanup-via-awx.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      awx-resource-deletion-playbook: delete-awx-cloudflare-ddns-deployment-resources.yaml
      awx-undeploy-template-name: Cloudflare%20DDNS%20%28Containerized%29%20-%20Remove
      ref: ${{ github.event.inputs.releaseRef }}
    secrets:
      VAULT_URL: ${{ github.event.inputs.environment == 'test' && secrets.VAULT_URL_TEST || secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ github.event.inputs.environment == 'test' && secrets.VAULT_TOKEN_TEST || secrets.VAULT_TOKEN }}
