---
name: PR Closed - Destroy Test Environment
run-name: PR ${{ github.event.number }} Closed Destroying Test Env

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  destroy-test:
    name: Destroy Test Environment
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-destroy-and-app-cleanup-via-awx.yaml@main
    with:
      environment: test
      awx-resource-deletion-playbook: delete-awx-cloudflare-ddns-deployment-resources.yaml
      awx-undeploy-template-name: Cloudflare%20DDNS%20%28Containerized%29%20-%20Remove
    secrets:
      VAULT_URL: ${{secrets.VAULT_URL_TEST}}
      VAULT_TOKEN: ${{secrets.VAULT_TOKEN_TEST}}
