---
name: PR Opened - Deploy To Test
run-name: Deploying PR ${{ github.event.number }} on ${{ github.head_ref }} To Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  deploy-to-test:
    name: Deploy To Test
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-apply-and-deploy-app-via-awx.yaml@main
    with:
      environment: test
      awx-resource-creation-script: create-awx-cloudflare-ddns-deployment-resources.yaml
      awx-deploy-template-name: Cloudflare%20DDNS%20%28Containerized%29%20-%20Deploy
    secrets:
      VAULT_URL: ${{secrets.VAULT_URL_TEST}}
      VAULT_TOKEN: ${{secrets.VAULT_TOKEN_TEST}}
