---
name: PR Opened - Lint & Scan - Terraform
run-name: Terraform Change Detected In PR ${{ github.event.number }} on ${{ github.head_ref }} - Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - infra/**

jobs:
  lint-tf:
    runs-on: github-arc-runners
    permissions:
      contents: read
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js (Dependency For Other Action)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        env:
          AWS_ENDPOINT_URL_S3: ${{ secrets.S3_URL_TEST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_TEST }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY_TEST }}
          AWS_S3_STATE_BUCKET: ${{ secrets.S3_BUCKET_NAME_TEST }}
        run: |
          terraform init -backend-config="bucket=${AWS_S3_STATE_BUCKET}"

      - name: Init TFLint
        run: tflint --init

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Run TFLint
        run: tflint -f compact

  security-scan-tf:
    runs-on: github-arc-runners
    needs:
      - lint-tf
    defaults:
      run:
        working-directory: infrastructure/environments/${{ matrix.environment }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "config"
          scan-ref: "infra"
          hide-progress: true
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
