---
name: Push To Main - Release
run-name: Release for Push on ${{ github.ref_name }} ${{ github.run_number }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

permissions:
  contents: read

jobs:
  release:
    name: Release
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/semantic-release-to-gh.yaml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
  